//! @generated by tools/native_apps.py from native-apps.json: do not edit;
//! change the manifest and run the script (ADR 0004 §1).
//!
//! The native apps this shell can link, in link order: the modules
//! `apps::linked_modules()` pushes under each app's feature, and the
//! hosting each app gets by default on each target.

use makepad_app_module::AppModule;

/// An app's hosting on one target, as the manifest declares it.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Hosting {
    /// In the shell's process: a splash isolate per instance.
    Module,
    /// Its own process (`bin`), connected to the shell's hub.
    Process,
    /// Its own process on a Vulkan build in a Wayland session; in the
    /// shell's process otherwise (a process-only app: not there).
    ProcessIfVulkan,
    /// Not on this target: a process-only app (no module) where
    /// there are no processes.
    None,
}

/// Who shows the person a tool's live confirmation (ADR 0004 §8).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Confirm {
    /// The shell's own sheet (the assistant's confirm card).
    Host,
    /// The owning app's own sheet.
    App,
}

/// How the shell treats one of an app's assistant tools.
#[derive(Debug)]
pub struct ToolPolicy {
    pub tool: &'static str,
    pub confirm: Confirm,
    /// Whether a standing rule may answer its confirmation; `false`:
    /// only the person, live, every time (outside developer mode).
    pub auto_approvable: bool,
}

/// What a process-hosted instance may reach on the network (ADR 0004 §3).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Network {
    /// Nothing but the shell's hub on loopback.
    None,
    Any,
}

/// One `native-apps.json` entry, as far as the shell reads it.
#[derive(Debug)]
pub struct NativeApp {
    pub id: &'static str,
    /// The shell's Cargo feature that links it.
    pub feature: &'static str,
    /// The binary a process-hosted instance runs.
    pub bin: Option<&'static str>,
    pub macos: Hosting,
    pub windows: Hosting,
    pub linux: Hosting,
    pub android: Hosting,
    pub ios: Hosting,
    pub ohos: Hosting,
    pub wasm: Hosting,
    /// The `octos.*` services its reviewed entry grants it.
    pub octos: &'static [&'static str],
    /// Its assistant tools' confirmation rules (`agent.tool_policy`).
    pub tools: &'static [ToolPolicy],
    /// `sandbox.network`: what its OS sandbox lets it reach.
    pub network: Network,
    /// `sandbox.processes`: whether it may start child processes.
    pub processes: bool,
    /// `storage.accounts`: one folder (and agent) per account.
    pub accounts: bool,
    /// `storage.external`: `<root>[/<path>]:ro|rw` outside its jail.
    pub external: &'static [&'static str],
    /// The whole `storage` block as JSON, which the shell parses with
    /// `app_storage::StorageSpec` at startup (ADR 0004 §11).
    pub storage: &'static str,
    /// `agent.tools`: its own tools, the `tools.json` entries (a JSON
    /// array; empty when it declares none).
    pub tools_json: &'static str,
    /// `agent.generic_tools`: exactly the octos kernel tools its agent
    /// gets (none when empty; never octos's shell).
    pub generic_tools: &'static [&'static str],
    /// `agent.grants`: other apps' shareable tools its agent may call,
    /// as (owning app, tool).
    pub grants: &'static [(&'static str, &'static str)],
    /// `agent.system_tools`: its own read tools the system agent may
    /// call while the app runs (full names).
    pub system_tools: &'static [&'static str],
    /// `agent.budget`: its agent's tool calls per turn and per day
    /// (`None`: the shell's defaults).
    pub calls_per_turn: Option<u32>,
    pub calls_per_day: Option<u32>,
}

pub const APPS: &[NativeApp] = &[
    NativeApp {
        id: "rinx",
        feature: "app-rinx",
        bin: None,
        macos: Hosting::Module,
        windows: Hosting::Module,
        linux: Hosting::Module,
        android: Hosting::Module,
        ios: Hosting::Module,
        ohos: Hosting::Module,
        wasm: Hosting::Module,
        octos: &["octos.session.open", "octos.session.history", "octos.turn.start", "octos.turn.interrupt"],
        tools: &[],
        network: Network::Any,
        processes: false,
        accounts: true,
        external: &[],
        storage: r#"{"accounts": true, "agent_workspace": "account", "external": []}"#,
        tools_json: r##"[]"##,
        generic_tools: &["read_file", "write_file", "edit_file", "diff_edit", "apply_patch", "glob", "grep", "list_dir", "code_structure", "ask_user_question", "view_image", "recall", "recall_memory", "memory_search", "memory_load", "save_memory", "memory_note", "web_search", "web_fetch", "tool_search"],
        grants: &[],
        system_tools: &[],
        calls_per_turn: None,
        calls_per_day: None,
    },
    NativeApp {
        id: "reference",
        feature: "app-reference",
        bin: Some("octosense-reference"),
        macos: Hosting::Module,
        windows: Hosting::Module,
        linux: Hosting::Module,
        android: Hosting::Module,
        ios: Hosting::Module,
        ohos: Hosting::Module,
        wasm: Hosting::Module,
        octos: &[],
        tools: &[],
        network: Network::None,
        processes: false,
        accounts: false,
        external: &[],
        storage: r#"{"accounts": false, "agent_workspace": "none", "external": []}"#,
        tools_json: r##"[]"##,
        generic_tools: &[],
        grants: &[],
        system_tools: &[],
        calls_per_turn: None,
        calls_per_day: None,
    },
    NativeApp {
        id: "sheets",
        feature: "app-sheets",
        bin: Some("sheets"),
        macos: Hosting::Module,
        windows: Hosting::Module,
        linux: Hosting::Module,
        android: Hosting::Module,
        ios: Hosting::Module,
        ohos: Hosting::Module,
        wasm: Hosting::Module,
        octos: &[],
        tools: &[],
        network: Network::None,
        processes: false,
        accounts: false,
        external: &[],
        storage: r#"{"accounts": false, "agent_workspace": "none", "external": []}"#,
        tools_json: r##"[]"##,
        generic_tools: &[],
        grants: &[],
        system_tools: &[],
        calls_per_turn: None,
        calls_per_day: None,
    },
    NativeApp {
        id: "terminal",
        feature: "app-terminal",
        bin: Some("terminal"),
        macos: Hosting::Process,
        windows: Hosting::Process,
        linux: Hosting::ProcessIfVulkan,
        android: Hosting::Module,
        ios: Hosting::Module,
        ohos: Hosting::Module,
        wasm: Hosting::Module,
        octos: &[],
        tools: &[
            ToolPolicy { tool: "run", confirm: Confirm::Host, auto_approvable: false },
        ],
        network: Network::Any,
        processes: true,
        accounts: false,
        external: &["home:rw"],
        storage: r#"{"accounts": false, "agent_workspace": "none", "external": ["home:rw"]}"#,
        tools_json: r##"[{"name":"terminal.run","description":"Type a command followed by Enter into the person's live Terminal. The person approves each command first, on a sheet that shows it exactly; it then runs for real in the terminal they see, inside the Terminal's own sandbox: the person's files and the network are reachable, OctoSense's private data and the build toolchain are not. It returns at once: the output is on the Terminal's screen.","input_schema":{"type":"object","properties":{"command":{"type":"string","maxLength":4096}},"required":["command"],"additionalProperties":false},"risk":"destructive","confirm":"host","shareable":true},{"name":"terminal.read_screen","description":"Read the terminal grid that is visible now, with trailing spaces removed from each row, plus cursor and working-directory context.","input_schema":{"type":"object","properties":{},"additionalProperties":false},"risk":"read","shareable":true},{"name":"terminal.read_scrollback","description":"Read the last requested number of lines from the terminal's scrollback plus screen (default 200, at most 2000).","input_schema":{"type":"object","properties":{"lines":{"type":"integer","minimum":1,"maximum":2000}},"additionalProperties":false},"risk":"read","shareable":true}]"##,
        generic_tools: &[],
        grants: &[],
        system_tools: &[],
        calls_per_turn: None,
        calls_per_day: None,
    },
    NativeApp {
        id: "appcard",
        feature: "app-appcard",
        bin: None,
        macos: Hosting::Module,
        windows: Hosting::Module,
        linux: Hosting::Module,
        android: Hosting::Module,
        ios: Hosting::Module,
        ohos: Hosting::Module,
        wasm: Hosting::Module,
        octos: &[],
        tools: &[],
        network: Network::Any,
        processes: false,
        accounts: false,
        external: &[],
        storage: r#"{"accounts": false, "agent_workspace": "none", "external": []}"#,
        tools_json: r##"[]"##,
        generic_tools: &[],
        grants: &[],
        system_tools: &[],
        calls_per_turn: None,
        calls_per_day: None,
    },
    NativeApp {
        id: "apphub",
        feature: "app-hub",
        bin: None,
        macos: Hosting::Module,
        windows: Hosting::Module,
        linux: Hosting::Module,
        android: Hosting::Module,
        ios: Hosting::Module,
        ohos: Hosting::Module,
        wasm: Hosting::Module,
        octos: &[],
        tools: &[],
        network: Network::Any,
        processes: false,
        accounts: false,
        external: &[],
        storage: r#"{"accounts": false, "agent_workspace": "none", "external": []}"#,
        tools_json: r##"[]"##,
        generic_tools: &[],
        grants: &[],
        system_tools: &[],
        calls_per_turn: None,
        calls_per_day: None,
    },
    NativeApp {
        id: "calculator",
        feature: "app-calculator",
        bin: Some("calculator"),
        macos: Hosting::Module,
        windows: Hosting::Module,
        linux: Hosting::Module,
        android: Hosting::Module,
        ios: Hosting::Module,
        ohos: Hosting::Module,
        wasm: Hosting::Module,
        octos: &["octos.session.open", "octos.session.history", "octos.turn.start", "octos.turn.interrupt"],
        tools: &[],
        network: Network::None,
        processes: false,
        accounts: false,
        external: &[],
        storage: r#"{"accounts": false, "agent_workspace": "none", "external": []}"#,
        tools_json: r##"[{"name":"calculator.eval","description":"Evaluate an expression. Uses the on-screen angle mode. Does not change the calculation, memory, or history.","input_schema":{"type":"object","properties":{"expression":{"type":"string","maxLength":1024}},"required":["expression"],"additionalProperties":false},"risk":"read","shareable":true}]"##,
        generic_tools: &[],
        grants: &[],
        system_tools: &["calculator.eval"],
        calls_per_turn: None,
        calls_per_day: None,
    },
    NativeApp {
        id: "clock",
        feature: "app-clock",
        bin: Some("clock"),
        macos: Hosting::Module,
        windows: Hosting::Module,
        linux: Hosting::Module,
        android: Hosting::Module,
        ios: Hosting::Module,
        ohos: Hosting::Module,
        wasm: Hosting::Module,
        octos: &["octos.session.open", "octos.session.history", "octos.turn.start", "octos.turn.interrupt"],
        tools: &[],
        network: Network::None,
        processes: false,
        accounts: false,
        external: &[],
        storage: r#"{"accounts": false, "agent_workspace": "none", "external": []}"#,
        tools_json: r##"[{"name":"clock.now","description":"The current local time and date, the next alarm, and any running timer or stopwatch.","input_schema":{"type":"object","properties":{}},"risk":"read","shareable":true}]"##,
        generic_tools: &[],
        grants: &[],
        system_tools: &["clock.now"],
        calls_per_turn: None,
        calls_per_day: None,
    },
    NativeApp {
        id: "notes",
        feature: "app-notes",
        bin: Some("notes"),
        macos: Hosting::Module,
        windows: Hosting::Module,
        linux: Hosting::Module,
        android: Hosting::Module,
        ios: Hosting::Module,
        ohos: Hosting::Module,
        wasm: Hosting::Module,
        octos: &["octos.session.open", "octos.session.history", "octos.turn.start", "octos.turn.interrupt"],
        tools: &[],
        network: Network::None,
        processes: false,
        accounts: false,
        external: &[],
        storage: r#"{"accounts": false, "agent_workspace": "none", "external": []}"#,
        tools_json: r##"[{"name":"notes.search","description":"Find active notes whose title or body contains the query. Answers id, title, preview, folder, edited_ms and pinned.","input_schema":{"type":"object","properties":{"query":{"type":"string","description":"text to find"}},"required":["query"]},"risk":"read","shareable":true},{"name":"notes.read","description":"Read one active note by id: folder, title, complete source, timestamps and pinned state.","input_schema":{"type":"object","properties":{"id":{"type":"string","description":"note id such as n000001"}},"required":["id"]},"risk":"read","shareable":true}]"##,
        generic_tools: &[],
        grants: &[],
        system_tools: &["notes.search", "notes.read"],
        calls_per_turn: None,
        calls_per_day: None,
    },
    NativeApp {
        id: "reminders",
        feature: "app-reminders",
        bin: Some("reminders"),
        macos: Hosting::Module,
        windows: Hosting::Module,
        linux: Hosting::Module,
        android: Hosting::Module,
        ios: Hosting::Module,
        ohos: Hosting::Module,
        wasm: Hosting::Module,
        octos: &["octos.session.open", "octos.session.history", "octos.turn.start", "octos.turn.interrupt"],
        tools: &[],
        network: Network::None,
        processes: false,
        accounts: false,
        external: &[],
        storage: r#"{"accounts": false, "agent_workspace": "none", "external": []}"#,
        tools_json: r##"[{"name":"reminders.due","description":"Incomplete dated reminders due before today plus N days, including overdue items and today.","input_schema":{"type":"object","properties":{"days":{"type":"integer","minimum":1,"maximum":31}},"required":["days"],"additionalProperties":false},"risk":"read","shareable":true},{"name":"reminders.list","description":"Reminders in a smart list or personal list, using the same projection as the UI.","input_schema":{"type":"object","properties":{"name":{"type":"string","minLength":1,"maxLength":64}},"required":["name"],"additionalProperties":false},"risk":"read","shareable":true}]"##,
        generic_tools: &[],
        grants: &[],
        system_tools: &["reminders.due", "reminders.list"],
        calls_per_turn: None,
        calls_per_day: None,
    },
    NativeApp {
        id: "weather",
        feature: "app-weather",
        bin: Some("weather"),
        macos: Hosting::Module,
        windows: Hosting::Module,
        linux: Hosting::Module,
        android: Hosting::Module,
        ios: Hosting::Module,
        ohos: Hosting::Module,
        wasm: Hosting::Module,
        octos: &["octos.session.open", "octos.session.history", "octos.turn.start", "octos.turn.interrupt"],
        tools: &[],
        network: Network::Any,
        processes: false,
        accounts: false,
        external: &[],
        storage: r#"{"accounts": false, "agent_workspace": "none", "external": []}"#,
        tools_json: r##"[{"name":"weather.current","description":"Current conditions and the 5-day forecast for the city selected on screen.","input_schema":{"type":"object","properties":{}},"risk":"read","shareable":true}]"##,
        generic_tools: &[],
        grants: &[],
        system_tools: &["weather.current"],
        calls_per_turn: None,
        calls_per_day: None,
    },
    NativeApp {
        id: "task",
        feature: "app-task",
        bin: Some("task"),
        macos: Hosting::Process,
        windows: Hosting::Process,
        linux: Hosting::ProcessIfVulkan,
        android: Hosting::None,
        ios: Hosting::None,
        ohos: Hosting::None,
        wasm: Hosting::None,
        octos: &[],
        tools: &[],
        network: Network::None,
        processes: true,
        accounts: false,
        external: &[],
        storage: r#"{"accounts": false, "agent_workspace": "none", "external": []}"#,
        tools_json: r##"[]"##,
        generic_tools: &[],
        grants: &[],
        system_tools: &[],
        calls_per_turn: None,
        calls_per_day: None,
    },
];

impl NativeApp {
    /// Its hosting on the target this shell is built for.
    pub const fn on_this_target(&self) -> Hosting {
        if cfg!(target_arch = "wasm32") {
            self.wasm
        } else if cfg!(target_os = "android") {
            self.android
        } else if cfg!(target_os = "ios") {
            self.ios
        } else if cfg!(target_env = "ohos") {
            self.ohos
        } else if cfg!(target_os = "macos") {
            self.macos
        } else if cfg!(target_os = "windows") {
            self.windows
        } else {
            self.linux
        }
    }
}

impl NativeApp {
    /// The rule for one of its tools, if the manifest sets one.
    pub fn tool(&self, name: &str) -> Option<&'static ToolPolicy> {
        self.tools.iter().find(|rule| rule.tool == name)
    }
}

/// The manifest entry for an app id.
pub fn find(id: &str) -> Option<&'static NativeApp> {
    APPS.iter().find(|app| app.id == id)
}

/// The Cargo package (`crate`) of an app with a `bin`: what a process
/// launch builds from the workspace, `cargo build --locked -p
/// octosense-process-apps -p <package>` (crates/process-apps).
pub fn package_of(id: &str) -> Option<&'static str> {
    match id {
        "reference" => Some("octosense-reference"),
        "sheets" => Some("makepad-sheets"),
        "terminal" => Some("makepad-terminal"),
        "calculator" => Some("makepad-calculator"),
        "clock" => Some("makepad-clock"),
        "notes" => Some("makepad-notes"),
        "reminders" => Some("makepad-reminders"),
        "weather" => Some("makepad-weather"),
        "task" => Some("makepad-task"),
        _ => None,
    }
}

/// Push the native modules this build links, in manifest order.
#[allow(unused_variables)]
pub fn link(out: &mut Vec<&'static dyn AppModule>) {
    #[cfg(feature = "app-rinx")]
    out.push(&rinx::module::RINX_MODULE);
    #[cfg(any(feature = "app-reference", native_mobile))]
    out.push(&octosense_reference::REFERENCE_MODULE);
    #[cfg(any(feature = "app-sheets", native_mobile))]
    out.push(&makepad_sheets::SHEETS_MODULE);
    #[cfg(feature = "app-terminal")]
    out.push(&makepad_terminal::TERMINAL_MODULE);
    #[cfg(feature = "app-appcard")]
    out.push(&octosense_appcard::APPCARD_MODULE);
    #[cfg(any(feature = "app-hub", native_mobile))]
    {
        out.push(&octosense_app_hub_app::APP_HUB_MODULE);
        out.push(&octosense_app_hub_app::CARD_MODULE);
    }
    #[cfg(feature = "app-calculator")]
    out.push(&makepad_calculator::CALCULATOR_MODULE);
    #[cfg(feature = "app-clock")]
    out.push(&makepad_clock::CLOCK_MODULE);
    #[cfg(feature = "app-notes")]
    out.push(&makepad_notes::NOTES_MODULE);
    #[cfg(feature = "app-reminders")]
    out.push(&makepad_reminders::REMINDERS_MODULE);
    #[cfg(feature = "app-weather")]
    out.push(&makepad_weather::WEATHER_MODULE);
}
