//! @generated by tools/native_apps.py from native-apps.json: do not edit;
//! change the manifest and run the script (ADR 0004 §1, §4).
//!
//! The native apps whose reviewed entry grants their agent `octos.*`
//! services (`agent.octos`): what [`crate::Policy::shipped`] hands out.

/// (app id, the `octos.*` services its agent is granted).
pub const NATIVE_AGENTS: &[(&str, &[&str])] = &[
    ("rinx", &["octos.session.open", "octos.session.history", "octos.turn.start", "octos.turn.interrupt"]),
    ("calculator", &["octos.session.open", "octos.session.history", "octos.turn.start", "octos.turn.interrupt"]),
    ("clock", &["octos.session.open", "octos.session.history", "octos.turn.start", "octos.turn.interrupt"]),
    ("notes", &["octos.session.open", "octos.session.history", "octos.turn.start", "octos.turn.interrupt"]),
    ("reminders", &["octos.session.open", "octos.session.history", "octos.turn.start", "octos.turn.interrupt"]),
    ("weather", &["octos.session.open", "octos.session.history", "octos.turn.start", "octos.turn.interrupt"]),
];
